"""Renames department model

Revision ID: 04c144a01b38
Revises: e2d18ed43be5
Create Date: 2024-10-04 17:25:56.987399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c144a01b38'
down_revision = 'e2d18ed43be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
